// Spice Pizza — Printer Bridge (local service)
//
// v1 (now): a tiny zero-dependency HTTP service that ACKNOWLEDGES print jobs so the
//           counter app can wire the "send to printer / printer offline / retry" flow.
//           The actual paper output for now is a PDF generated by the web app.
// v2 (when hardware arrives): implement escpos() below to print to a USB/network
//           thermal printer via `node-thermal-printer`. See README.md.
//
// Run:  npm start   (listens on PORT, default 4000)

import http from "node:http";

const PORT = process.env.PORT || 4000;
const PRINTER_MODE = process.env.PRINTER_MODE || "stub"; // stub | usb | network

function json(res, code, body) {
  const data = JSON.stringify(body);
  res.writeHead(code, {
    "content-type": "application/json",
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "content-type",
    "access-control-allow-methods": "GET,POST,OPTIONS",
  });
  res.end(data);
}

function readBody(req) {
  return new Promise((resolve) => {
    let raw = "";
    req.on("data", (c) => (raw += c));
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch {
        resolve({});
      }
    });
  });
}

// Placeholder for real thermal printing. Implement when a printer is connected.
async function escpos(job) {
  // Example (v2):
  //   import { printer as ThermalPrinter, types } from "node-thermal-printer";
  //   const printer = new ThermalPrinter({ type: types.EPSON, interface: process.env.PRINTER_INTERFACE });
  //   ... build slip from job ... await printer.execute();
  throw new Error("ESC/POS printing not implemented yet (PRINTER_MODE=stub). PDF is produced by the web app.");
}

const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") return json(res, 204, {});

  if (req.method === "GET" && req.url === "/health") {
    return json(res, 200, { ok: true, mode: PRINTER_MODE, service: "spice-pizza-printer-bridge" });
  }

  if (req.method === "POST" && req.url === "/print") {
    const job = await readBody(req);
    // job = { kind: "kitchen" | "counter" | "bill", orderId, roundId?, lines: [...], meta: {...} }
    console.log(`[print] ${new Date().toISOString()} kind=${job.kind} order=${job.orderId ?? "-"} lines=${(job.lines || []).length}`);
    if (PRINTER_MODE === "stub") {
      return json(res, 200, { ok: true, mode: "stub", printed: false, note: "Acknowledged. Connect a printer + set PRINTER_MODE to print paper." });
    }
    try {
      await escpos(job);
      return json(res, 200, { ok: true, mode: PRINTER_MODE, printed: true });
    } catch (err) {
      return json(res, 503, { ok: false, error: String(err.message || err) });
    }
  }

  return json(res, 404, { ok: false, error: "not found" });
});

server.listen(PORT, () => {
  console.log(`Spice Pizza printer-bridge listening on http://localhost:${PORT} (mode=${PRINTER_MODE})`);
});
