// Spice Pizza — Printer Bridge (local service)
//
// v1 (stub): acknowledges print jobs; PDF is generated by the web app.
// v2 (now):  pdf_spooler mode — lists Windows printers via wmic and
//            forwards PDF files to a selected Windows printer using
//            PowerShell / SumatraPDF.
//
// Run:  npm start   (listens on PORT, default 4000)

import http from "node:http";
import { exec, execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const execAsync = promisify(exec);
const PORT = process.env.PORT || 4000;
const PRINTER_MODE = process.env.PRINTER_MODE || "stub"; // stub | pdf_spooler | network | usb

function json(res, code, body) {
  const data = JSON.stringify(body);
  res.writeHead(code, {
    "content-type": "application/json",
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "content-type",
    "access-control-allow-methods": "GET,POST,OPTIONS",
  });
  res.end(data);
}

function readBody(req) {
  return new Promise((resolve) => {
    let raw = "";
    req.on("data", (c) => (raw += c));
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch {
        resolve({});
      }
    });
  });
}

// ──────────────────────────────────────────────────────────────────
// Windows Printer Discovery via WMIC
// ──────────────────────────────────────────────────────────────────
async function listWindowsPrinters() {
  try {
    // Try wmic first (available on all Windows versions)
    const { stdout } = await execAsync(
      'wmic printer get Name,Default,WorkOffline,PrinterStatus /format:csv',
      { timeout: 8000 }
    );
    const lines = stdout.trim().split(/\r?\n/).filter(Boolean);
    if (lines.length < 2) return [];

    const header = lines[0].split(",").map((h) => h.trim().toLowerCase());
    const printers = [];
    for (let i = 1; i < lines.length; i++) {
      const cols = lines[i].split(",");
      if (cols.length < header.length) continue;
      const row = {};
      header.forEach((h, idx) => { row[h] = (cols[idx] || "").trim(); });
      const name = row["name"] || row["printer name"] || "";
      if (!name) continue;
      printers.push({
        name,
        isDefault: row["default"] === "TRUE",
        status: row["printerstatus"] === "3" ? "ready" : row["printerstatus"] === "4" ? "printing" : "unknown",
        offline: row["workoffline"] === "TRUE",
      });
    }
    return printers;
  } catch (err) {
    console.warn("[printers] wmic failed, trying PowerShell:", err.message);
  }

  // Fallback: PowerShell Get-Printer
  try {
    const { stdout } = await execAsync(
      'powershell -NoProfile -Command "Get-Printer | Select-Object Name,Default,PrinterStatus | ConvertTo-Json -Compress"',
      { timeout: 10000 }
    );
    const raw = JSON.parse(stdout.trim());
    const arr = Array.isArray(raw) ? raw : [raw];
    return arr.map((p) => ({
      name: p.Name || "",
      isDefault: !!p.Default,
      status: p.PrinterStatus === 3 ? "ready" : "unknown",
      offline: false,
    })).filter((p) => p.name);
  } catch (err2) {
    console.error("[printers] PowerShell fallback also failed:", err2.message);
    return [];
  }
}

// ──────────────────────────────────────────────────────────────────
// Print a PDF to a named Windows printer
// ──────────────────────────────────────────────────────────────────
async function printPdfToWindows(pdfBase64, printerName, copies = 1) {
  // Write PDF to a temp file
  const tmpDir = os.tmpdir();
  const tmpFile = path.join(tmpDir, `spice_print_${Date.now()}.pdf`);
  const pdfBuffer = Buffer.from(pdfBase64, "base64");
  fs.writeFileSync(tmpFile, pdfBuffer);

  console.log(`[print] Sending to Windows printer: "${printerName}" (${copies} copies) — ${tmpFile}`);

  // Try SumatraPDF first (most reliable silent PDF printing on Windows)
  const sumatraPaths = [
    "C:\\Program Files\\SumatraPDF\\SumatraPDF.exe",
    "C:\\Program Files (x86)\\SumatraPDF\\SumatraPDF.exe",
    "SumatraPDF.exe", // if in PATH
  ];

  for (const sumatraPath of sumatraPaths) {
    if (sumatraPath !== "SumatraPDF.exe" && !fs.existsSync(sumatraPath)) continue;
    try {
      const cmd = `"${sumatraPath}" -print-to "${printerName}" -print-settings "${copies}x" -silent "${tmpFile}"`;
      await execAsync(cmd, { timeout: 30000 });
      fs.unlink(tmpFile, () => {});
      return { method: "SumatraPDF", printer: printerName };
    } catch (err) {
      console.warn(`[print] SumatraPDF at ${sumatraPath} failed:`, err.message);
    }
  }

  // Fallback: PowerShell Out-Printer
  try {
    const ps = `Start-Process -FilePath "${tmpFile}" -Verb Print -PassThru | Wait-Process -Timeout 30`;
    // For named printer, use: rundll32 printui.dll,PrintUIEntry
    // Most reliable cross-version method:
    const psCmd = `powershell -NoProfile -Command "
      $job = Start-Process -FilePath '${tmpFile}' -Verb PrintTo -ArgumentList '\\"${printerName}\\"' -PassThru;
      Start-Sleep -Seconds 5;
      if ($job -and !$job.HasExited) { $job.Kill() };
      exit 0
    "`;
    await execAsync(psCmd.replace(/\n/g, " "), { timeout: 30000 });
    fs.unlink(tmpFile, () => {});
    return { method: "PrintTo-verb", printer: printerName };
  } catch (err) {
    fs.unlink(tmpFile, () => {});
    throw new Error(`Could not print to "${printerName}": ${err.message}. Install SumatraPDF for reliable PDF printing.`);
  }
}

// ──────────────────────────────────────────────────────────────────
// HTTP Server
// ──────────────────────────────────────────────────────────────────
const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") return json(res, 204, {});

  // ── GET /health ─────────────────────────────────────────────────
  if (req.method === "GET" && req.url === "/health") {
    return json(res, 200, {
      ok: true,
      mode: PRINTER_MODE,
      service: "spice-pizza-printer-bridge",
      platform: os.platform(),
      version: "2.0.0",
    });
  }

  // ── GET /printers ───────────────────────────────────────────────
  // Lists all printers available on this Windows machine.
  if (req.method === "GET" && req.url === "/printers") {
    try {
      const printers = await listWindowsPrinters();
      return json(res, 200, { ok: true, printers });
    } catch (err) {
      return json(res, 500, { ok: false, error: String(err.message || err) });
    }
  }

  // ── POST /print ─────────────────────────────────────────────────
  if (req.method === "POST" && req.url === "/print") {
    const job = await readBody(req);
    // job = { kind, orderId, lines, meta, pdfBase64?, printerName?, copies? }
    console.log(
      `[print] ${new Date().toISOString()} kind=${job.kind} order=${job.orderId ?? "-"} printer=${job.printerName ?? "default"} mode=${PRINTER_MODE}`
    );

    if (PRINTER_MODE === "stub") {
      return json(res, 200, {
        ok: true, mode: "stub", printed: false,
        note: "Stub mode: job acknowledged. Set PRINTER_MODE=pdf_spooler to print via Windows.",
      });
    }

    if (PRINTER_MODE === "pdf_spooler") {
      if (!job.pdfBase64) {
        return json(res, 400, { ok: false, error: "pdfBase64 is required for pdf_spooler mode." });
      }
      if (!job.printerName) {
        return json(res, 400, { ok: false, error: "printerName is required. Call GET /printers to list available printers." });
      }
      try {
        const result = await printPdfToWindows(job.pdfBase64, job.printerName, job.copies || 1);
        return json(res, 200, { ok: true, mode: "pdf_spooler", printed: true, ...result });
      } catch (err) {
        return json(res, 503, { ok: false, error: String(err.message || err) });
      }
    }

    // ESC/POS network/USB modes (placeholder for thermal printer)
    return json(res, 501, {
      ok: false,
      error: `PRINTER_MODE=${PRINTER_MODE} not yet implemented. Use pdf_spooler or stub.`,
    });
  }

  return json(res, 404, { ok: false, error: "not found" });
});

server.listen(PORT, () => {
  console.log(`\n🖨️  Spice Pizza printer-bridge v2.0`);
  console.log(`   Listening on http://localhost:${PORT}`);
  console.log(`   Mode: ${PRINTER_MODE}`);
  console.log(`   Platform: ${os.platform()} ${os.release()}\n`);
  console.log(`   Endpoints:`);
  console.log(`     GET  /health    — bridge status`);
  console.log(`     GET  /printers  — list Windows printers`);
  console.log(`     POST /print     — send a print job\n`);
  if (PRINTER_MODE === "stub") {
    console.log(`   ⚠️  Running in stub mode. Set PRINTER_MODE=pdf_spooler to enable real printing.\n`);
  }
});
